// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCVtDG8Oh8PNKwgjwyLmsgFaCNsvOyiY',
    appId: '1:129387226201:web:49b9e5b092d6b9253bfd48',
    messagingSenderId: '129387226201',
    projectId: 'taskify-a182c',
    authDomain: 'taskify-a182c.firebaseapp.com',
    databaseURL: 'https://taskify-a182c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskify-a182c.appspot.com',
    measurementId: 'G-NJ0G1J4KDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjEVxxgrqU8FCZgQmV-GBBPHnxBTx3ic',
    appId: '1:129387226201:android:503af7157bd818233bfd48',
    messagingSenderId: '129387226201',
    projectId: 'taskify-a182c',
    databaseURL: 'https://taskify-a182c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskify-a182c.appspot.com',
  );
}
